### ISSUE TITLE
Missing `lodash` dependency in package.json

### ISSUE THREAD

**Issue by hacknug** [webdna/tailwindcss-aspect-ratio#6]
When using [pnpm](https://pnpm.js.org/) to install my project's dependencies I'm getting the following error:

```bash
Message:
    Cannot find module 'lodash'
Details:
    code: MODULE_NOT_FOUND
    fileName: /Users/nestor/my-project/assets/css/main.pcss
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/nestor/my-project/node_modules/.registry.npmjs.org/tailwindcss-aspect-ratio/1.0.1/node_modules/tailwindcss-aspect-ratio/index.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

I'm guessing it should be listed inside `dependencies` instead of `devDependencies`: https://github.com/webdna/tailwindcss-aspect-ratio/blob/master/package.json#L25-L27

**Comment by nfourtythree** [comment]
hi @hacknug 

I have moved this into dependencies and also updated lodash to fix the vulnerability issue

Thanks!
